version: '3.8'
services:
  backend:
    build: ./student_code_evaluator/backend
    container_name: codebuddy-backend
    ports:
      - "5001:5000"
    volumes:
      - codebuddy_db_data:/app/backend
    restart: unless-stopped

  frontend:
    build: ./student_code_evaluator/app
    container_name: codebuddy-frontend
    ports:
      - "8501:8501"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  codebuddy_db_data: 